# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbc040f8f24fceb69b43e8da516668b0c9242cd6a96291b7ef94e8927fb9cdcc0db2649ddbeb02b56559607bb23e6a6207907c319330913e5e9a87de51e545d9

test:
  secret_key_base: d20edc40b75c18c0e8fa2729bb815d67b81c2442430c6f4ccdabe427474432988173396aad358d1fd4f29f9366988fe916b1fed152024dcfab14ee964cf93448

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
