# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 625c3c275063c017f39ea433fc9c579a5158b022207826e48b2fecaa645942cb37d375dc133476dd7ca110e093d8594b9d4c915f267f1cc2d25e6280ca235574

test:
  secret_key_base: 87eee9b2dd54edcd05c9fe98f7b7b3c7684b74f77431ee2fb337056e4f48c24a124274d4b2af9b231afe11dc2a5f38504a5c6baa972247ccefb9fd614833ca80

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
